'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { ArrowRight, CheckCircle2, Loader2, Sparkles } from 'lucide-react'
import { PasswordInput } from './PasswordInput'

export function SignupCard() {
  const [submitted, setSubmitted] = useState(false)
  const [loading, setLoading] = useState(false)
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); window.setTimeout(() => { setLoading(false); setSubmitted(true) }, 550) }
  if (submitted) return <div className="w-full max-w-[500px] rounded-[2rem] bg-white border border-white p-8 sm:p-10 shadow-[0_24px_70px_rgba(30,64,175,.12)] text-center"><div className="w-14 h-14 rounded-2xl bg-emerald-50 text-emerald-600 grid place-items-center mx-auto"><CheckCircle2 size={27}/></div><p className="mt-6 text-xs font-bold tracking-[.15em] text-emerald-600">REQUEST RECEIVED</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">You&apos;re on the list.</h1><p className="mt-3 text-sm leading-6 text-slate-500">A LaundryOS specialist will reach out with the next steps to set up your workspace.</p><Link href="/login" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">Back to sign in <ArrowRight size={16}/></Link></div>
  return <div className="w-full max-w-[500px]"><div className="lg:hidden flex items-center gap-2 mb-8"><div className="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-600 to-indigo-700 grid place-items-center text-white font-extrabold">L</div><span className="font-extrabold text-xl tracking-tight">Laundry<span className="text-blue-600">OS</span></span></div><div className="rounded-[2rem] bg-white/90 backdrop-blur-xl border border-white p-7 sm:p-9 shadow-[0_24px_70px_rgba(30,64,175,.12)]"><p className="inline-flex items-center gap-1.5 text-xs font-bold tracking-[.13em] text-blue-600"><Sparkles size={13}/> START YOUR WORKSPACE</p><h1 className="mt-3 text-3xl font-extrabold tracking-tight text-slate-950">Build a calmer laundry operation.</h1><p className="mt-2 text-sm leading-6 text-slate-500">Tell us about your team. We&apos;ll help set up the workspace that fits your flow.</p><form onSubmit={submit} className="mt-7 grid gap-4"><div className="grid sm:grid-cols-2 gap-4"><Field label="Your name" name="name" placeholder="Jane Njeri"/><Field label="Business name" name="business" placeholder="FreshFold Laundry"/></div><Field label="Work email" name="email" type="email" placeholder="you@business.co.ke"/><div className="grid sm:grid-cols-2 gap-4"><Field label="Team size" name="team" placeholder="e.g. 8 people"/><div><label className="block text-sm font-semibold text-slate-700 mb-1.5">Phone number</label><input name="phone" required placeholder="+254 700 000 000" className="w-full h-11 px-4 rounded-xl border border-slate-200 bg-slate-50 outline-none focus:bg-white focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/></div></div><div><label className="block text-sm font-semibold text-slate-700 mb-1.5">Create password</label><PasswordInput name="password" minLength={8} required placeholder="At least 8 characters" className="rounded-xl"/></div><label className="flex gap-2 text-xs leading-5 text-slate-500"><input required type="checkbox" className="mt-1 accent-blue-600"/>I agree to be contacted about setting up my LaundryOS workspace.</label><button disabled={loading} className="h-12 mt-1 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-bold shadow-lg shadow-blue-200 inline-flex items-center justify-center gap-2 disabled:opacity-70">{loading ? <><Loader2 size={17} className="animate-spin"/> Sending request</> : <>Request workspace setup <ArrowRight size={17}/></>}</button></form><p className="mt-6 text-center text-sm text-slate-500">Already have a workspace? <Link href="/login" className="font-bold text-blue-600">Sign in</Link></p></div></div>
}
function Field({ label, ...props }: { label: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <div><label htmlFor={props.name} className="block text-sm font-semibold text-slate-700 mb-1.5">{label}</label><input id={props.name} required className="w-full h-11 px-4 rounded-xl border border-slate-200 bg-slate-50 outline-none transition-all focus:bg-white focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10" {...props}/></div> }
